### PR TITLE
Removed isFirefox check from Zoom.js

### PR DESCRIPTION
**Pull request by HippoDippo**
This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/119.

### CODE REVIEW

**Comment by rpearce** [comment]
👀

**Comment by HippoDippo** [comment]
Everything look correct? 😰

**Comment by rpearce** [comment]
I've cloned your repo and am going through the examples to be sure! Code looks fine, and I am just double checking :)

**Comment by HippoDippo** [comment]
Oh good! Had me nervous there for a second :)

**Comment by rpearce** [comment]
looks good to me! I'll merge this, add some changelog notes, add you to all contributors section of README.

**Comment by HippoDippo** [comment]
Yayyyyy! 🎉 Thanks for all your help! If you don't mind, I am definitely going to dive into the code and get familiar with it so i can continue contributing :)

**Comment by rpearce** [comment]
Next steps for you: if you don't want to contribute again, you can just delete this project on your side.

If you do:
1. click the "delete branch" button here
1. `git checkout master`
1. `git origin add upstream git@github.com:rpearce/react-medium-image-zoom.git`
1. `git fetch upstream`
1. `git rebase upstream/master`
1. `git branch -D remove-firefox-check` to remove the branch on your computer

This will add the root project as being "upstream" from you, and you can always pull down the latest `master` branch from this project to your fork's master branch.

Note: never do any work in your fork's `master` branch -- always in a "feature branch" like we did here!

* * *

Also be aware that this library is not the simplest to follow through the code, unfortunately (that's what happens with time and the nature of being a library sometimes), so please open an issue if you have an implementation or general question.

**Comment by HippoDippo** [comment]
Ohh ok.

**Comment by rpearce** [comment]
@HippoDippo go check out the all-contributors section on the root project page and the `AUTHORS` file, as well

**Comment by HippoDippo** [comment]
That is awesome! Thank you for the opportunity!

**Comment by HippoDippo** [comment]
Also it would be cool if you told me what you think on this small project i'm building.
Link: https://www.npmjs.com/package/stylze

**Comment by rpearce** [comment]
@HippoDippo couple of things:
* does it have a repository? I don't see one listed
* it doesn't look like the markdown is formatted correctly for code blocks, making it difficult to read
* what makes this project more efficient than using `style={{ color: blue, background: red }}` on JSX elements or https://www.npmjs.com/package/styled-components or CSS modules or ____? Share your story about _why_ this exists and what benefit it brings others
* are there really issues with installing it via `npm`? what are they and why? that should probably be figured out before publishing

**Comment by HippoDippo** [comment]
Ohh ok sorry.

**Comment by rpearce** [comment]
@HippoDippo Nothing to be sorry about! We're all on the path somewhere. After doing a quick review, those were the first things I noticed, so I shared them.

**Comment by HippoDippo** [comment]
I appreciate it! I will probably take it down because it does not serve a purpose. The only thing it does that makes it unique, is that you can pass in an event handler as an argument for the buttons. It was just a fun thing i was hacking on and experimenting with while learning react. Again, appreciate the pointers.

**Comment by rpearce** [comment]
Keep experimenting!

**Comment by HippoDippo** [comment]
@rpearce I built a small tool for something i am building, and i was hoping i can get some more pointers. Here is the link: https://www.npmjs.com/package/genkey

**Comment by rpearce** [comment]
@HippoDippo While this is quite clever, the concept breaks a core concept of React & functional programming in that the React app will have to dispose of your old `h3` (in the example) and create a new one _on every render_! The purpose of `key={}` is so that React can keep a reference to a component; however, if the `key` is changed every time, then that component is no longer tracked and a new one is (imagine if you had a component where you had `state` set – you would lose your state every time, I believe.).

* * *

Separately, I don't think this is valid JS:
```js
let userNames = names.map((name, index) => {
  return (
    return <h3 key={genkey(33, true)}>{name}</h3>;
  );
});
```
What I think you meant was:
```js
const userNames = names.map(name => {
  return (
    <h3 key={genkey(33, true)}>{name}</h3>;
  );
});
```
but I would just write it as 
```js
names.map(x =>
  <h3 key={genkey(33, true)}>{name}</h3>
)
```
and put that inside a function or class method that accepts a `name` parameter.

* * *

I recommend naming library docs with ALL_CAPS to make it easy to find and be just like every other library. So `Readme.md` should be `README.md`.

* * *

A challenge: see if you can make your functions in `genkey/index.js` not assign _any_ variables and use zero `for () {}` loops and accomplish the same goal.

**Comment by HippoDippo** [comment]
I noticed my mistake and fixed it on npm, but forgot about GitHub. And thank you for your time and advice! I am eager to learn and improve so i appreciate it! As for the challenge, i gladly accept. I am assuming by not using any for loops, i am permitted to use the array methods?

**Comment by rpearce** [comment]
Absolutely! -- `map`, `filter`, `reduce`, `forEach` are all great ways of working with lists. It should also be noted that `reduce` can literally do anything/everything (though sometimes it shouldn't). Check out this slide deck on "reduce is the omnifunction": https://omnifunction.herokuapp.com/

Also, instead of using this issue to keep asking things, maybe use twitter -- @RobertWPearce -- so we can include others that might want to participate and leave this poor pull request alone :)

**Comment by HippoDippo** [comment]
Awesome thank you! I will check it out! And haha "this poor pull request" 😂 I agree, that's my fault.

**Pull request merged**
