### PR TITLE
Portalize <dialog> to avoid invalid HTML issues

### PR DESCRIPTION
**Pull request by rpearce**
## Description

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/356 ~by adding `wrapElement` back to the API. Honestly, I forgot about https://github.com/rpearce/react-medium-image-zoom/pull/238~.

~However, allowing `<span>` or `<p>` or any element that can only have "Phrasing content" (inline elements, really) as a parent creates an issue, for the `<dialog>` element is block-level. To remediate this, I'm seeing if leveraging a portal for the `<dialog>` is a wise decision.~ It seems that the portal might be the way to go. Continued testing will have the final say.

### CODE REVIEW

**Comment by rpearce** [comment]
- [ ] This breaks the styling and customization of the modal per https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--custom-modal-styles, so that's something to figure out.

**Comment by Songkeys** [comment]
I couldn't think of a better way to do this without introducing a styling breaking change. Even using web-component, the shadow dom will prevent the styling injection.

I haven't tried yet. But a possible solution in my head:

using a hidden dummy dom playing as the `dialog` to get the style:

```diff
      <WrapElement>
+       <span data-rmiz-modal="" hidden aria-hidden ref={dummyDialogRef}>
+         <span data-rmiz-modal-overlay={dataOverlayState} />
+         <span data-rmiz-modal-content=""></span>
+       </span>
        
        {hasImage && document?.body != null && createPortal(
          <dialog>
            ...
          </dialog>
          , document.body
        )}
      </WrapElement>
```

We get the styling that user injected from `dummyDialogRef` and inject that into the real `dialog` dynamically.

This is verbose but hopefully a method for not introducing breaking change.

---

In the next major version, I would suggest using this way to inject styles:

```jsx
<Zoom
  styles={{ root: {}, wrapper: {}, dialog: {}, ... }}
  classNames={{ root: "", wrapper: "", dialog: "", ... }}
>
  ...
</Zoom>
```

to ensure that we blackbox the api well enough.

**Comment by rpearce** [comment]
Thanks for your thoughts here. The first 3 version of this project took the object style props approach, exactly as you suggest, and there may have even been the classname approach.

The maintenance of this was unmanageable, and it made it very difficult to adjust the markup without introducing breaking changes.

Thank you again for your time. I'm a little busy at night for the next few days and haven't been able to circle back around.

**Comment by rpearce** [comment]
- [ ] Clicking on the background seems to not be closing it

**Comment by rpearce** [comment]
@Songkeys I may have a pretty simple solution here that isn't significant departure. I hacked something out with the spare time I had tonight, and `react-medium-image-zoom@5.1.0-beta.3` has the latest code here, plus the unreleased https://github.com/rpearce/react-medium-image-zoom/pull/344, if you want to give it a go.

I still need to test this across screen readers, and I'll get to that as soon as I can.

**Comment by Songkeys** [comment]
Not working for me. I still get the error validateDOMNesting(...): <div> cannot appear as a descendant of <p>. The dom structure doesn't seem to change. Did you build the code and test?

**Comment by rpearce** [comment]
> I still need to test this across screen readers and SSR usage, too. I'll get to them as soon as I can.

The SSR aspect could be the case. I will try it as soon as I can with NextJS (maybe tonight?) and get back to you.

**Comment by rpearce** [comment]
Ah, I pulled out the `wrapElement` things prematurely. This is what I get for only having late evenings to do open source work.

**Comment by rpearce** [comment]
@Songkeys `react-medium-image-zoom@5.1.0-beta.4`, when provided `wrapElement="span"`, should now be working for you and not causing that error. Please let me know what else is giving you trouble!

I ran a brand new nextjs + TypeScript project, and I didn't have any issues (apart from https://github.com/rpearce/react-medium-image-zoom/pull/358#issuecomment-1258909281, which I need to fix).

**Comment by Songkeys** [comment]
I tried in my project. It works really well. What an amazing work! Thank you so much for bringing this feature and maintaining this repo for years!

(I wish I could sponsor you for the work but it doesn't support my country 😞. I'll watch this repo to see if there is anything i can help.)

Thank you again!!

**Comment by rpearce** [comment]
@Songkeys Perfect! I will merge this into that dev branch, I will let you know when 5.1.0 is officially released, and I will add you to the all contributors list for your amazing collaboration here.

**Pull request merged**
