### PR TITLE
Prioritize prop styles over computed styles

### PR DESCRIPTION
**Pull request by xerona**
This pull request closes (past link to GitHub issue here).

## Pre-Flight Checklist
I have made sure to
- [ ] make sure this PR is set to merge to the correct `X-0-stable` branch
- [ ] add a Storybook example (if necessary)
- [ ] manually test all the Storybook examples
  * run `$ yarn run storybook`
  * navigate to http://localhost:6006
- [ ] run `$ yarn run build` to build the project code & static example
- [ ] check that the example in `example/build/index.html` works: `$ open example/build/index.html`

### CODE REVIEW

**Comment by rpearce** [comment]
Hi, @xerona; thank you for this submission! Could you please share more about the problem you're having and share a way to reproduce the problem so I can fully understand what you're experiencing and what this fix accomplishes for you?

**Comment by xerona** [comment]
Sure. In one particular case, I had a very long but narrow image with text. Rather than fit the container, I wanted to allow scrolling of the focused image. Much of the component's behavior was still desireable. I wanted the background obscured and the image both centered and magnified. I tried to add some styles to accommodate the scenario and allow for the image to fit the full width but overflow the height and scroll. As I was trying to adjust styles computed and provided by the component, they were overwritten.
It's not a pretty example, but I was creating an `ImageZoom` component much like this.
```
 <ImageZoom
  image={{src: path}}
  defaultStyles={{
    zoomContainer: {overflow: 'scroll'},
    overlay: { position: 'fixed', width: '100%', height: '100%' },
    image: { width: '100%' },
    zoomImage: { width: '100%', height: 'initial', transform: 'none', top: '0', left: '0', padding: '50px' }
  }}
/>
```

**Comment by rpearce** [comment]
@xerona Thanks for explaining that. Would you be able to provide an image like the one you're talking about or have a demo setup somewhere that can show the issue? That would make the issue a lot easier to understand.

This is a big change being requested, so I need to understand as best I can! Thank you for your patience.

**Comment by xerona** [comment]
https://codesandbox.io/s/exciting-nash-ckkhj
`ScrollableImageZoom` is my current workaround to accommodate my needs. I can't get my branch loaded as a dependency for comparison, so I have `3.1.1` and my hack so you can see the difference. The image I've used isn't great quality but imagine more legible text when zoomed.

**Comment by rpearce** [comment]
@xerona Thank you! I will review ASAP -- we're moving to a new house and will be settled after this weekend.

**Comment by rpearce** [comment]
This PR will no long be able to be applied to the `master` branch, as that is now the development branch for the `v4.0` rewrite. If this is something you're still interested in, please verify it against the [v3.x](https://github.com/rpearce/react-medium-image-zoom/tree/v3.x) branch.

I apologize for the trouble.

**Comment by rpearce** [comment]
Closing this PR as stale and in potential future favor of a new one to the `v3.x` branch

**Pull request closed without merging**
