### PR TITLE
Calculate imageCenterX with clientWidth

### PR DESCRIPTION
**Pull request by ludwigfrank**
Calculate "imageCenterX" with "clientWidth" to include the scrollbar width.

### CODE REVIEW

**Comment by rpearce** [comment]
@ludwigfrank Thank you for contributing! This makes sense. I'll review it more thoroughly shortly and add you to the contributors list upon merging.

**Comment by rpearce** [comment]
:+1:

**Comment by rpearce** [comment]
This has been published under version `3.0.13`, and you've been added as a contributor in the `AUTHORS` file, as well as the "All Contributors" section in the `README`. Thanks again!

**Comment by ludwigfrank** [comment]
Thank you so much for maintaining this project I'm happy to contribute! 👍

**Pull request merged**
