### PR TITLE
Proptypes update

### PR DESCRIPTION
**Pull request by rpearce**
cc @ismay and this PR: https://github.com/rpearce/react-medium-image-zoom/pull/39

### CODE REVIEW

**Comment by ismay** [comment]
Looks good! One thing I'd suggest though is to make this a breaking change, as people who upgrade and don't have the prop-types package will break their builds.

**Comment by rpearce** [comment]
@ismay damn I knew that was a bad idea. As I understand it, a breaking change merits a major version bump, correct?

**Comment by ismay** [comment]
> damn I knew that was a bad idea

Not necessarily, there was a similar discussion here: https://github.com/airbnb/enzyme/pull/876#issuecomment-293647836. It's kind of a grey area I guess.

But if you'd consider it a breaking change a major version bump would reflect that. I personally wouldn't sweat it though as you've already released.

Also, thanks for the quick update! 🎉

**Comment by rpearce** [comment]
Reading semver docs and it seems kind of gray area

**Comment by ismay** [comment]
Yeah exactly

**Comment by rpearce** [comment]
I'm going to bump to 0.10 – do you think I should unpublish 0.9.2?

**Comment by ismay** [comment]
If you want to indicate that this is a breaking change I'd follow this strategy: https://github.com/airbnb/enzyme/pull/876#issuecomment-293747239.

So publish a revert in 0.9.3 and put the breaking changes in 1.0.0

**Comment by rpearce** [comment]
I don't like the idea of unpublishing, though.

This isn't a breaking _API_ change, to me, so I'm okay with 0.10

**Comment by rpearce** [comment]
(your comment was delayed)

okay i like where your head is at

**Comment by rpearce** [comment]
@ismay I've never done that before, but I think I did it alright. I did this:
* checked out a branch
* reset my code to before today and published that as 0.9.3
* checked out master, did a major bump, merged that
* published 1.0.0 as the latest

**Comment by ismay** [comment]
>  I've never done that before, but I think I did it alright.

I think so too, see these greenkeeper notifications:

* https://github.com/ismay/ismaywolff.nl/issues/314#issuecomment-293842428 (0.9.3 fixed the 0.9.2 breaking build)
* https://github.com/ismay/ismaywolff.nl/pull/315 (separate pr for the upgrade to 1.0.0)

Looks good!

**Comment by rpearce** [comment]
Wicked. Thanks!

**Comment by ismay** [comment]
Happy to help! 👍

**Pull request merged**
