### PR TITLE
Update Zoom.js for issue #119

### PR DESCRIPTION
**Pull request by HippoDippo**
Fixes open issue #119. If i did not correctly fix it then apologies.

### CODE REVIEW

**Comment by rpearce** [comment]
@HippoDippo thank you for opening this pull request!

If you see the [Contributing Instructions](https://github.com/rpearce/react-medium-image-zoom#contributing) in the README, step number 6 asks that you please run the command `$ yarn run build` in order to rebuild the example file. Would you mind doing that? Thanks in advance.

(Was this code updated via the GitHub web interface?)

Also, it's generally a good idea to include a commit message that says what the commit is about, such as "Removed isFirefox check from Zoom.js".

**Comment by rpearce** [comment]
@HippoDippo Also, if you need help with anything I just said above, please let me know, and I can guide you through it.

**Comment by HippoDippo** [comment]
Ohh ok i'm sorry! And yes it was done through the GitHub web interface. I will git clone it and then do yarn run build!

**Comment by HippoDippo** [comment]
Do i need to close this PR?

**Comment by rpearce** [comment]
@HippoDippo No worries! When you have done that and committed the result, I'll check out your repository & branch and make sure it's all good before merging.

If you are not comfortable with interactive rebasing in order to combine two commits and reword the first one, then yes, I would close this one and open a new one with 
  * the code changes
  * a descriptive commit message

**Comment by rpearce** [comment]
I'm also happy to explain exactly how to do an interactive rebase

**Comment by HippoDippo** [comment]
If you don't mind i would love to learn it. Sorry i pretty new to this. Also after i git cloned the repo and ran yarn run build, it says 'Cannot find module eslint-plugin-react'. Is this because i need to run yarn add or npm install?

**Comment by HippoDippo** [comment]
Running npm install and then yarn run build worked.

**Comment by rpearce** [comment]
If you did it through the interface, then I think that means you don't actually have the work you did from before in this `patch-1` branch? So here's what you do:

1. `git checkout -b remove-firefox-check`
1. make your changes in the `Zoom.js` file
1. `yarn run build`
1. `open docs/index.html` (to make sure the example works correctly)
1. `git add -A; git commit -m "Removed isFirefox check from Zoom.js"`
1. `git push origin remove-firefox-check`
1. go to your fork of the repository on GitHub's web interface
1. you should see a button for "new pull request" for your branch pop up (big green button)
1. fill out the information you would like to and make sure the pull request is set to be merged to rpearce:master
1. create pull request!

**Comment by HippoDippo** [comment]
Ok will do! Just to clarify, i need to run npm install before yarn run build?

**Comment by rpearce** [comment]
Just `yarn` should install the dependencies. If you don’t have yarn, then `npm i && npm run build` will do, instead.

**Comment by HippoDippo** [comment]
Ok awesome thank you!

**Pull request closed without merging**
